### ISSUE TITLE
RedisWeekly

### ISSUE THREAD

**Issue by FGRibreau** [MichaelXavier/redis-rdb-parser#1]
Hello @MichaelXavier !

Okay, it's still a work in progress but the code was really interesting to read, redis-rdb-parser will be shared in our next [RedisWeekly](http://redisweekly.com) tomorrow morning!

**Comment by MichaelXavier** [comment]
Cool! Thanks for letting me know. The types and parsers are still kind of a mess but this turned out to be kind of a treasure trove of interesting, focused problems to solve. It required me to write implementations of [crc](https://github.com/michaelxavier/crc) and bindings to [liblzf](https://github.com/michaelxavier/lzf-bytestring) for compression which may be worth mentioning in your newsletter.
